### ISSUE TITLE
solargraph command not found despite being in gemfile

### ISSUE THREAD

**Issue by Nitrodist** [neoclide/coc-solargraph#41]
I've tried to use the solargraph server that coc.nvim + coc-solargraph tries to launch but I get this almost every time and configuration I use:

```
[coc.nvim] Failed to start Solargraph: Gem::Exception: can't find executable solargraph for gem solargraph. solargraph is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Users/mark.campbell/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /Users/mark.campbell/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
  /Users/mark.campbell/.asdf/installs/ruby/2.5.1/bin/solargraph:23:in `<top (required)>'
```

I'm using asdf for ruby/rails and zsh as my shell (presumably.. I have no idea how to check which shell the coc.nvim or coc-solargraph actually invokes). My .zprofile has a line for the asdf plugin and even an extra line to shove in where the bin path is to ensure it's correct.

Running `bundle exec solargraph socket` and setting the coc-solargraph config to 'transport' works well enough. It's a bit of a pain to do it though, but it's a workaround that works.

I've spent a fair amount of time trying to debug it with different useBundler settings and commandPath settings etc. all to no avail and it's a bit frustrating haha.

**Comment by chemzqm** [comment]
Install solargraph globally and make sure you can execute solargraph in your shell.

**Comment by lightcap** [comment]
It seems like global (to your ruby version) is the only real option if you're not using rvm or rbenv. Using chruby would be possible if the `bundlerPath` config option would handle environment vars like `$GEM_HOME`.

At least that's my quick take. If someone wants to validate that I can look at making a PR.

Here's the line that makes it clear that it's not going to expand any vars that aren't explicitly replaced.

https://github.com/neoclide/coc-solargraph/blob/3ee67401bedef9ffadf10408ee94b42ae7e85941/src/index.ts#L15
